# Generated by Django 3.1.4 on 2021-05-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('SG', 'Selection Game'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('FI', 'Final')], default='SG', max_length=6)),
                ('game_id', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('final_score', models.IntegerField(default=0)),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('who_won', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COACH', 'Coach'), ('PLAYER', 'Player'), ('ADMIN', 'Admin')], default='PLAYER', max_length=6)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('average_score', models.FloatField()),
                ('no_of_games', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.team')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.user')),
            ],
        ),
        migrations.CreateModel(
            name='TeamGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_score', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.game')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.team')),
            ],
        ),
    ]
