# Generated by Django 3.1.4 on 2021-05-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='game',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
        migrations.AlterModelTable(
            name='teamgame',
            table='team_game',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usergame',
            table='user_game',
        ),
        migrations.AlterModelTable(
            name='userteam',
            table='user_team',
        ),
    ]
