# Generated by Django 3.1.4 on 2021-05-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20210502_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='team_id',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='api_basic.team'),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api_basic.user'),
        ),
    ]
